With amol As (Select rd.smiles_to_rdmol('c1ccccc1C(=O)NC N‐methylbenzamide', false, true) As rdmol) Select rd.version()
, rd.cansmiles(rdmol)
, rd.isosmiles(rdmol)
, rd.keksmiles(rdmol)
, rd.impsmiles(rdmol)
, rd.graph(rdmol)
, rd.inchi(rdmol)
, rd.inchikey(rdmol)
, rd.matches(rdmol, 'C=O')
, rd.count_matches(rdmol, 'c')
, rd.list_matches(rdmol, 'C[O,N]', 0)
, length(rd.fp(rdmol))
, oc.nbits_set(rd.fp(rdmol))
, rd.fpbits(rdmol)
, rd.smiles_to_symbols(rdmol)
, rd.smiles_to_bonds(rdmol)
, oc.glogp(rdmol)
, oc.tpsa(rdmol)
, oc.amw(rdmol)
, oc.tanimoto(rd.fp(rdmol), rd.fp(rd.rdmol('c1ccccc1C=O')))
, rd.mcs(Array[rdmol, rd.rdmol('c1ccccc1')])
, rd.molfile_to_smiles(rd.molfile(rdmol))
, rd.molfile_property(rd.molfile(rdmol), '_Name')
From amol;
